name: Daily Cron Job

on:
  schedule:
    - cron: '0 23 * * *' 

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Run my task
        env:
          MY_API_URL: ${{ secrets.API_URL }}
        run: |
          # You can now access the URL using $MY_API_URL
          echo "API URL: $MY_API_URL"
